version: '3.9'
name: restaurant-location-service
services:
  restaurant-location-api:
    container_name: restaurant-location-api
    image: pins/restaurant-location-api
    depends_on:
      restaurant-location-db:
        condition: service_healthy
    networks:
      - restaurant-location-net
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: Dockerfile.api
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}

  restaurant-location-db:
    container_name: restaurant-location-db
    image: pins/restaurant-location-db
    networks:
      - restaurant-location-net
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U devuser -d restaurant_location_db"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - restaurant-location-db-vol:/var/lib/postgresql/database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  restaurant-location-db-vol:


networks:
  restaurant-location-net:
    driver: bridge
